#!/bin/sh -x

#--image-family=centos-7 \
gcloud compute instances create oscars1 \
    --image=https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20170223 \
    --machine-type=n1-standard-1 \
    --metadata-from-file startup-script=./gce-startup-script \
    --zone=us-central1-c    
